//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абонент
    {
        public Абонент()
        {
            this.Телефон = new HashSet<Телефон>();
        }
    
        public int Id_Абонента { get; set; }
        public string ФИО { get; set; }
        public string Адрес_проживания { get; set; }
    
        public virtual ICollection<Телефон> Телефон { get; set; }
    }
}
