//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разговоры
    {
        public int Номер_разговора { get; set; }
        public string Дата_разговора { get; set; }
        public Nullable<int> продолжительность { get; set; }
        public string Признак_оплаты { get; set; }
        public string Номер_Телефона { get; set; }
        public Nullable<int> Код_города { get; set; }
    
        public virtual Тариф Тариф { get; set; }
        public virtual Телефон Телефон { get; set; }
    }
}
