//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace session
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефон
    {
        public Телефон()
        {
            this.Разговоры = new HashSet<Разговоры>();
        }
    
        public string Номер_Телефона { get; set; }
        public string Номер_договора { get; set; }
        public string Дата_установки { get; set; }
        public Nullable<int> Id_абонента { get; set; }
    
        public virtual Абонент Абонент { get; set; }
        public virtual ICollection<Разговоры> Разговоры { get; set; }
    }
}
